//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql3
{
    using System;
    using System.Collections.Generic;
    
    public partial class carparkdetail
    {
        public int CarParkID { get; set; }
        public string CarParkName { get; set; }
        public string CarParkAddress { get; set; }
        public string Resolution { get; set; }
        public int Frequency { get; set; }
        public string ImageName { get; set; }
    }
}
