//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EparkApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class space
    {
        public int ID { get; set; }
        public int CarPark { get; set; }
        public bool Status { get; set; }
        public float x1 { get; set; }
        public float y1 { get; set; }
        public float x2 { get; set; }
        public float y2 { get; set; }
        public float x3 { get; set; }
        public float y3 { get; set; }
        public float x4 { get; set; }
        public float y4 { get; set; }
    
        public virtual carpark carpark1 { get; set; }
    }
}
