//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EparkDatabaseEntities : DbContext
    {
        public EparkDatabaseEntities()
            : base("name=EparkDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarParkTbl> CarParkTbls { get; set; }
        public virtual DbSet<LocationTbl> LocationTbls { get; set; }
        public virtual DbSet<SpaceTbl> SpaceTbls { get; set; }
    }
}
